volumes:
  fastapi-travel-threads-data:
    external: true
services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://travel_user:secret@db/travel_threads
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  db:
    image: postgres:15.2-bullseye
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: travel_user
      POSTGRES_DB: travel_threads
    ports:
      - "5432:5432"
    volumes:
      - fastapi-travel-threads-data:/var/lib/postgresql/data
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
